CREATE TABLE "HW12_container" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HW12_container_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT NOW() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "HW12_error" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HW12_error_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"agentId" integer NOT NULL,
	"containerId" integer NOT NULL,
	"serviceName" varchar(256) DEFAULT 'unknown' NOT NULL,
	"errorMessage" varchar(4096) NOT NULL,
	"explaination" varchar(4096) NOT NULL,
	"suggestedFix" varchar(4096) NOT NULL,
	"resolved" boolean DEFAULT false NOT NULL,
	"resolvedAt" timestamp with time zone,
	"occurredAt" timestamp with time zone DEFAULT NOW() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "HW12_status" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HW12_status_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"containerId" integer NOT NULL,
	"status" varchar(256) NOT NULL,
	"checkedInAt" timestamp with time zone DEFAULT NOW() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "HW12_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HW12_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(256) NOT NULL,
	"name" varchar(256) NOT NULL,
	"phoneNumber" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT NOW() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "HW12_waitlist" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HW12_waitlist_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(256) NOT NULL,
	"note" varchar(1024),
	"createdAt" timestamp with time zone DEFAULT NOW() NOT NULL,
	CONSTRAINT "HW12_waitlist_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "HW12_error" ADD CONSTRAINT "HW12_error_containerId_HW12_container_id_fk" FOREIGN KEY ("containerId") REFERENCES "public"."HW12_container"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "HW12_status" ADD CONSTRAINT "HW12_status_containerId_HW12_container_id_fk" FOREIGN KEY ("containerId") REFERENCES "public"."HW12_container"("id") ON DELETE cascade ON UPDATE no action;