CREATE TABLE "HW12_agent_command" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HW12_agent_command_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"agentId" integer NOT NULL,
	"containerId" integer NOT NULL,
	"action" varchar(16) NOT NULL,
	"status" varchar(16) DEFAULT 'pending' NOT NULL,
	"result" varchar(1024),
	"createdAt" timestamp with time zone DEFAULT NOW() NOT NULL,
	"completedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "HW12_agent" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HW12_agent_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"lastSeen" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT NOW() NOT NULL,
	CONSTRAINT "HW12_agent_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "HW12_container" ADD COLUMN "agentId" integer;--> statement-breakpoint
ALTER TABLE "HW12_error" ADD COLUMN "resolvedBy" varchar(16);--> statement-breakpoint
ALTER TABLE "HW12_error" ADD COLUMN "resolution" varchar(1024);--> statement-breakpoint
ALTER TABLE "HW12_agent_command" ADD CONSTRAINT "HW12_agent_command_agentId_HW12_agent_id_fk" FOREIGN KEY ("agentId") REFERENCES "public"."HW12_agent"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "HW12_agent_command" ADD CONSTRAINT "HW12_agent_command_containerId_HW12_container_id_fk" FOREIGN KEY ("containerId") REFERENCES "public"."HW12_container"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "HW12_container" ADD CONSTRAINT "HW12_container_agentId_HW12_agent_id_fk" FOREIGN KEY ("agentId") REFERENCES "public"."HW12_agent"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "HW12_container" ADD CONSTRAINT "HW12_container_name_unique" UNIQUE("name");